# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Valet_Parking_ValetSide' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Valet_Parking_ValetSide
  pod 'MBProgressHUD', '~> 1.0.0'
  # pod 'AFNetworkActivityLogger', '~> 2.0.4'
  pod 'INTULocationManager', '~> 4.2.0'
  pod 'UMengAnalytics', '~> 4.0.4'
  pod 'NJKWebViewProgress', '~> 0.2.3'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'JSONModel', '~> 1.3.0'
  pod 'QRCodeReaderViewController', '~> 4.0.2'
  pod 'CBStoreHouseRefreshControl'

  target 'Valet_Parking_ValetSideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Valet_Parking_ValetSideUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
